 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.FondoVentana;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Lnv
 */
public class Administrador extends javax.swing.JFrame {
     String username,nomusu;
    
    /**
     * Creates new form Administrador
     */
     public Administrador(){
         initComponents();
     }
    public Administrador(String username,String nomusu) {
        initComponents();
        this.username=username;
        this.nomusu=nomusu;
        setTitle("Administrador");
        setResizable(false);
        setLocationRelativeTo(null);
        
       lnombreusuario.setText("Bienvenido "+nomusu);
       
       FondoVentana fondo=new FondoVentana();
       fondo.FondoVentas(this);
      
    }
    @Override
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnombreusuario = new javax.swing.JLabel();
        btnregistrarusuario = new javax.swing.JButton();
        btngestionarusuario = new javax.swing.JButton();
        btncreatividad = new javax.swing.JButton();
        btncapturista = new javax.swing.JButton();
        btntecnico = new javax.swing.JButton();
        btnacercade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 170, 0, 0));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(350, 170));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(660, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnombreusuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lnombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        lnombreusuario.setText("jLabel1");
        getContentPane().add(lnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnregistrarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        btnregistrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, 100));

        btngestionarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        btngestionarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestionarusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btngestionarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 100));

        btncreatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        btncreatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatividadActionPerformed(evt);
            }
        });
        getContentPane().add(btncreatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 120, 100));

        btncapturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        btncapturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapturistaActionPerformed(evt);
            }
        });
        getContentPane().add(btncapturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 100));

        btntecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tecnico.png"))); // NOI18N
        btntecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(btntecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 100));

        btnacercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/m.png"))); // NOI18N
        btnacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacercadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnacercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestionar Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Creatividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Panel Vista Capturista");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Panel Vista Tecnico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Acerca De");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Creado Por Marlon ®");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarusuarioActionPerformed
        new RegistrarUsuario(username).setVisible(true);
    }//GEN-LAST:event_btnregistrarusuarioActionPerformed

    private void btngestionarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionarusuarioActionPerformed
        new UsuariosRegistrados(username).setVisible(true);
    }//GEN-LAST:event_btngestionarusuarioActionPerformed

    private void btncapturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapturistaActionPerformed
        new Capturista(username, nomusu).setVisible(true);
    }//GEN-LAST:event_btncapturistaActionPerformed

    private void btntecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntecnicoActionPerformed
       new Tecnico(username, nomusu).setVisible(true);
    }//GEN-LAST:event_btntecnicoActionPerformed

    private void btnacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacercadeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_btnacercadeActionPerformed

    private void btncreatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatividadActionPerformed
        new Creatividad().setVisible(true);
    }//GEN-LAST:event_btncreatividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacercade;
    private javax.swing.JButton btncapturista;
    private javax.swing.JButton btncreatividad;
    private javax.swing.JButton btngestionarusuario;
    private javax.swing.JButton btnregistrarusuario;
    private javax.swing.JButton btntecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lnombreusuario;
    // End of variables declaration//GEN-END:variables
}
