/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorGraficaEstatus;
import controlador.FondoVentana;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Lnv
 */
public class GraficaEstatus extends javax.swing.JFrame {
    boolean bandera;
    ControladorGraficaEstatus graficar=new ControladorGraficaEstatus();
    int nuevoingreso,noreparado,enrevision,reparado,entregado,otro;
    /**
     * Creates new form GraficaEstatus
     */
    
    public GraficaEstatus() {
        initComponents();
    }

    public GraficaEstatus(String username,boolean bandera) {
        initComponents();
        setLocationRelativeTo(null);  
        setResizable(false);
        setTitle("Tecnico - Sesion de "+username);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.bandera=bandera;
        
        FondoVentana fondo=new FondoVentana();
        fondo.FondoVentas(this);
        
        repaint();
        nuevoingreso=graficar.nuevoIngreso();
        noreparado=graficar.noReparado();
        enrevision=graficar.enRevision();
        reparado=graficar.reparado();
        entregado=graficar.entregado();
        otro=graficar.otro();
    }
     @Override
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
      
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grafica de Estatus");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Creado por Marlon ®");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaEstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
   @Override
  public void paint(Graphics g){
      
       super.paint(g);
       if(bandera==true){
        
        int valormayor=graficar.mayorValor(nuevoingreso, noreparado, enrevision, reparado, entregado, otro);
        
        int ningreso=nuevoingreso*400/valormayor;
        int nreparados=noreparado*400/valormayor;
        int erevision=enrevision*400/valormayor;
        int reparados=reparado*400/valormayor;
        int entregados=entregado*400/valormayor;
        int otros=otro*400/valormayor;
        
        g.setColor(new Color(255,170,0));
        g.fillRect(100, 100, ningreso, 40);
        g.drawString("Nuevo ingreso", 10, 118);
        g.drawString("Cantida "+nuevoingreso, 10, 133);
        
        g.setColor(new Color(255,0,0));
        g.fillRect(100, 150, nreparados, 40);
        g.drawString("No reparados", 10, 168);
        g.drawString("Cantida "+noreparado, 10, 180);
        
        g.setColor(new Color(0,0,255));
        g.fillRect(100, 200, erevision, 40);
        g.drawString("En revision", 10, 218);
        g.drawString("Cantida "+enrevision, 10, 233);
        
        g.setColor(new Color(0,150,255));
        g.fillRect(100, 250, reparados, 40);
        g.drawString("Reparados", 10, 268);
        g.drawString("Cantida "+reparado, 10, 280);
        
        g.setColor(new Color(0,130,0));
        g.fillRect(100, 300, entregados, 40);
        g.drawString("Entregados", 10, 318);
        g.drawString("Cantida "+entregado, 10, 333);
        
        g.setColor(new Color(150,100,100));
        g.fillRect(100, 350, otros, 40);
        g.drawString("Otro", 10, 368);
        g.drawString("Cantida "+otro, 10, 380);
        
       }
  }
     
}
