/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.itextpdf.text.DocumentException;
import controlador.ControladorInfoCliente;
import controlador.ControladorReporteInfoCliente;
import controlador.FondoVentana;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Lnv
 */
public class InformacionDelCliente extends javax.swing.JFrame {
     String nomcli,username;
     int idcliente,idequipo;
     ControladorInfoCliente infocliente=new ControladorInfoCliente();
    /**
     * Creates new form InformacionDelCliente
     */
    public InformacionDelCliente() {
        initComponents();
    }
    public InformacionDelCliente(String nomcli,int idcliente,String username) {
        initComponents();
        this.nomcli=nomcli;
        this.username=username;
        this.idcliente=idcliente;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setTitle("Informacion del Cliente "+nomcli+" - sesion de "+username);
        jLabel1.setText("Informacion del Cliente "+nomcli);
       
        FondoVentana fondo=new FondoVentana();
        fondo.FondoVentas(this);
        
        infocliente.mostrarInfoCliente(idcliente, txtnomcli, txtmailcli, txttelcli, txtdircli, txtmodificadopor);
        infocliente.mostrarInfoEquipo(idcliente, jTable1);
        infocliente.setEventoMouseClicked(jTable1, username, nomcli);
    }
    @Override
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnomcli = new javax.swing.JTextField();
        txtmailcli = new javax.swing.JTextField();
        txttelcli = new javax.swing.JTextField();
        txtdircli = new javax.swing.JTextField();
        txtmodificadopor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnregistroequipos = new javax.swing.JButton();
        btnupdatecliente = new javax.swing.JButton();
        btnreporteinfocliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");

        txtnomcli.setBackground(new java.awt.Color(153, 153, 255));
        txtnomcli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnomcli.setForeground(new java.awt.Color(255, 255, 255));
        txtnomcli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnomcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomcliKeyReleased(evt);
            }
        });

        txtmailcli.setBackground(new java.awt.Color(153, 153, 255));
        txtmailcli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmailcli.setForeground(new java.awt.Color(255, 255, 255));
        txtmailcli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmailcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmailcliKeyReleased(evt);
            }
        });

        txttelcli.setBackground(new java.awt.Color(153, 153, 255));
        txttelcli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttelcli.setForeground(new java.awt.Color(255, 255, 255));
        txttelcli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelcliKeyReleased(evt);
            }
        });

        txtdircli.setBackground(new java.awt.Color(153, 153, 255));
        txtdircli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdircli.setForeground(new java.awt.Color(255, 255, 255));
        txtdircli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdircli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdircliKeyReleased(evt);
            }
        });

        txtmodificadopor.setEditable(false);
        txtmodificadopor.setBackground(new java.awt.Color(153, 153, 255));
        txtmodificadopor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmodificadopor.setForeground(new java.awt.Color(255, 255, 255));
        txtmodificadopor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmodificadopor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E - mail");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ultima Modificacion Por :");

        btnregistroequipos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnregistroequipos.setText("Registrar Equipos");
        btnregistroequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroequiposActionPerformed(evt);
            }
        });

        btnupdatecliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnupdatecliente.setText("Actualizar Cliente");
        btnupdatecliente.setEnabled(false);
        btnupdatecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateclienteActionPerformed(evt);
            }
        });

        btnreporteinfocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        btnreporteinfocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteinfoclienteActionPerformed(evt);
            }
        });

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Equipo", "Tipo De equipo", "Marca", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Creado por Marlon ®");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtmodificadopor, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdircli, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnregistroequipos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdatecliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnreporteinfocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmailcli, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txttelcli, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmailcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttelcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdircli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnregistroequipos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnupdatecliente, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(txtmodificadopor)))
                    .addComponent(btnreporteinfocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateclienteActionPerformed
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Desea modificar los datos actuales?");
        
        if (confirmar == JOptionPane.YES_OPTION) {
            infocliente.actualizarInfocliente(idcliente, txtnomcli, txtmailcli, txttelcli, txtdircli, username);
            dispose();
            
        } else {
            infocliente.mostrarInfoCliente(idcliente, txtnomcli, txtmailcli, txttelcli, txtdircli, txtmodificadopor);
        }
    }//GEN-LAST:event_btnupdateclienteActionPerformed

    private void btnregistroequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroequiposActionPerformed
        new RegistrarEquipos(idcliente,nomcli,username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregistroequiposActionPerformed

    private void btnreporteinfoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteinfoclienteActionPerformed
        try {
             ControladorReporteInfoCliente reporte=new ControladorReporteInfoCliente();
             reporte.reporte(idcliente);
         } catch (DocumentException ex) {
             Logger.getLogger(InformacionDelCliente.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnreporteinfoclienteActionPerformed

    private void txtnomcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomcliKeyReleased
        if(!infocliente.nombrecli.equals(txtnomcli.getText())){
            btnupdatecliente.setEnabled(true);
        }else{
            btnupdatecliente.setEnabled(false);
        }
    }//GEN-LAST:event_txtnomcliKeyReleased

    private void txtmailcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailcliKeyReleased
        if(!infocliente.correocli.equals(txtmailcli.getText())){
            btnupdatecliente.setEnabled(true);
        }else{
            btnupdatecliente.setEnabled(false);
        }
    }//GEN-LAST:event_txtmailcliKeyReleased

    private void txttelcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelcliKeyReleased
        if(!infocliente.telefcli.equals(txttelcli.getText())){
            btnupdatecliente.setEnabled(true);
        }else{
            btnupdatecliente.setEnabled(false);
        }
    }//GEN-LAST:event_txttelcliKeyReleased

    private void txtdircliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdircliKeyReleased
        if(!infocliente.direccli.equals(txtdircli.getText())){
            btnupdatecliente.setEnabled(true);
        }else{
            btnupdatecliente.setEnabled(false);
        }
    }//GEN-LAST:event_txtdircliKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionDelCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistroequipos;
    private javax.swing.JButton btnreporteinfocliente;
    private javax.swing.JButton btnupdatecliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdircli;
    private javax.swing.JTextField txtmailcli;
    private javax.swing.JTextField txtmodificadopor;
    private javax.swing.JTextField txtnomcli;
    private javax.swing.JTextField txttelcli;
    // End of variables declaration//GEN-END:variables
}
